{ config, pkgs, ... }:

{
  config = let
    # The teams-for-linux application uses a specific flag (--user-stylesheet)
    # to load a custom CSS file. We will use this flag in our wrapper.
    teams-for-linux-pywal-wrapper = pkgs.writeShellScriptBin "teams-for-linux" ''
      # Location of the pywal colors file.
      pywal_json="$HOME/.cache/wal/colors.json"
      
      # Location for the generated custom CSS file.
      # We use a hidden directory to keep it organized.
      custom_css="$HOME/.config/teams-for-linux/pywal-theme.css"
      
      # Ensure the directory exists.
      mkdir -p "$(dirname "$custom_css")"
      
      # Check if the pywal colors file exists before proceeding.
      if [ -f "$pywal_json" ]; then
          # Use jq to read the colors and create the CSS content.
          # We define CSS variables for each color to make theming easier.
          ${pkgs.jq}/bin/jq -r '
            "/* Generated by NixOS pywal-teams-theme-wrapper */\n
            :root {\n
              --background-color: \(.special.background);\n
              --foreground-color: \(.special.foreground);\n
              --color0: \(.colors.color0);\n
              --color1: \(.colors.color1);\n
              --color2: \(.colors.color2);\n
              --color3: \(.colors.color3);\n
              --color4: \(.colors.color4);\n
              --color5: \(.colors.color5);\n
              --color6: \(.colors.color6);\n
              --color7: \(.colors.color7);\n
              --color8: \(.colors.color8);\n
              --color9: \(.colors.color9);\n
              --color10: \(.colors.color10);\n
              --color11: \(.colors.color11);\n
              --color12: \(.colors.color12);\n
              --color13: \(.colors.color13);\n
              --color14: \(.colors.color14);\n
              --color15: \(.colors.color15);\n
            }\n
            body {\n
              background-color: var(--background-color);\n
              color: var(--foreground-color);\n
            }\n"
          ' "$pywal_json" > "$custom_css"
      fi
      
      # Execute the original teams-for-linux application with the correct flags.
      # The '--user-stylesheet' flag will now correctly load our theme file.
      exec ${pkgs.teams-for-linux}/bin/teams-for-linux \
        --enable-features=UseOzonePlatform,WaylandWindowDecorations \
        --ozone-platform=wayland \
        --customCSSLocation="$custom_css"
    '';
  in
  {
    environment.systemPackages = with pkgs; [
      teams-for-linux-pywal-wrapper
      jq # jq is required to parse the JSON file, so we install it as a dependency.
    ];
  };
}
